{
  label: "Tooling & Workflow",
  tools: [
    "Vite",
    "Bun",
    "Node.js",
    "ESLint",
    "Git",
    "GitHub",
    "GitHub Actions (CI/CD)",
    "Vercel",
    "Chrome DevTools",
    "Claude Code",
    "Codex",
    "Antigravity",
  ],
},